const JOIN_METHODS = [
  {
    id: "web",
    label: "Web link",
    when: "Recruitment emails, landing pages, posters with a URL",
    format: "https://samply.uni-konstanz.de/studies/your-study-slug",
    notes: [
      "Opens a browser page. The participant taps a button to hand off to the Samply Research app.",
      "Requires the study to be marked Currently active. Inactive studies show a “not available” message on this page.",
    ],
  },
  {
    id: "deep",
    label: "Direct deep link",
    when: "SMS, messaging apps, QR codes — anything that opens straight into the app",
    format: "samply://--/study?id=<study-id>",
    notes: [
      "Bypasses the browser landing page and opens the app directly.",
      "Works whether or not the study is currently active.",
      "Append &code=ABC to pre-fill the participant code field on enrolment.",
    ],
  },
  {
    id: "browse",
    label: "Browse in-app",
    when: "Lab sessions where participants use a shared device with the app already open",
    format: "— no link needed —",
    notes: [
      "Participants search for your study by name or ID from within the Samply Research app.",
    ],
  },
  {
    id: "secure",
    label: "Secure invitation link",
    when: "Longitudinal studies where each participant must receive a unique, time-limited link",
    format: "samply://register?study=…&validfor=…&checksum=…",
    notes: [
      "Generated on the Invitations page with a configurable validity window (default 168 hours = 7 days).",
      "The link is cryptographically signed — any tampering invalidates it.",
      "The generator has an optional Code field. Leave it blank for a link that any participant can use; enter a code to pre-fill that participant's identifier on enrolment, making the link effectively single-use for that person.",
      "A QR code for the generated link is rendered on-screen for easy scanning.",
    ],
  },
];

const PARTICIPANT_TABLE_COLUMNS = [
  { col: "Samply ID", desc: "Anonymous identifier generated by the app — never tied to a real name or email." },
  { col: "Token", desc: "The device's push notification token. Samply uses this to deliver notifications." },
  { col: "Date", desc: "When the participant enrolled." },
  { col: "Code", desc: "The custom identifier the participant entered, if your study asks for one." },
  { col: "Group", desc: "The group the participant was assigned to, if your study uses groups." },
  { col: "Timezone", desc: "Detected from the participant's device. Used to schedule personal notifications at the right local time." },
  { col: "Time window", desc: "The hours during which the participant prefers to receive notifications, set by the participant in the app. This does not affect scheduled send times — if you want to respect individual time preferences, you need to take this into account manually when configuring your notification schedules." },
  { col: "History", desc: "A per-participant log of every notification send and whether a survey response was detected." },
];

export default function InviteContent() {
  return (
    <>
      <p>
        Participants join through the <strong>Samply Research</strong> app, available for{" "}
        <a href="https://apps.apple.com/us/app/samply-research/id1511062019" target="_blank" rel="noopener noreferrer">iOS</a>{" "}
        and{" "}
        <a href="https://play.google.com/store/apps/details?id=org.js.samply" target="_blank" rel="noopener noreferrer">Android</a>.
        Participants must install the app before they can enrol in any study.
      </p>

      {/* ── Four methods ──────────────────────────────────────────────────── */}
      <h2>Four ways to invite</h2>
      <p>
        All four methods end at the same place: the participant is enrolled and their push notification
        token is registered. Pick the method that fits your recruitment channel.
      </p>

      <div style={{ display: "flex", flexDirection: "column", gap: "1.6rem", margin: "2.4rem 0 4rem" }}>
        {JOIN_METHODS.map((m) => (
          <div
            key={m.id}
            style={{ background: "var(--surface)", border: "1px solid var(--ink-10)", borderRadius: "1rem", padding: "2rem 2.2rem" }}
          >
            <div style={{ display: "flex", alignItems: "baseline", gap: "1.2rem", marginBottom: "0.8rem", flexWrap: "wrap" }}>
              <span style={{ fontFamily: "var(--font-display)", fontSize: "1.55rem", fontWeight: 700, color: "var(--ink)" }}>{m.label}</span>
              <span style={{ fontFamily: "var(--font-mono)", fontSize: "1.05rem", color: "var(--ink-40)", letterSpacing: "0.04em" }}>{m.when}</span>
            </div>
            <div style={{ fontFamily: "var(--font-mono)", fontSize: "1.15rem", color: "var(--coral)", background: "var(--coral-soft)", padding: "0.5rem 1rem", borderRadius: "0.5rem", marginBottom: "1rem", wordBreak: "break-all" }}>{m.format}</div>
            <ul style={{ margin: 0, paddingLeft: "1.6rem" }}>
              {m.notes.map((n, i) => (
                <li key={i} style={{ fontSize: "1.3rem", color: "var(--ink-60)", lineHeight: 1.6, marginBottom: "0.3rem" }}>{n}</li>
              ))}
            </ul>
          </div>
        ))}
      </div>

      {/* ── Participant experience ────────────────────────────────────────── */}
      <h2>What the participant sees</h2>
      <p>
        Before joining, participants must install the Samply Research app from the{" "}
        <a href="https://apps.apple.com/us/app/samply-research/id1511062019" target="_blank" rel="noopener noreferrer">App Store</a>{" "}
        or{" "}
        <a href="https://play.google.com/store/apps/details?id=org.js.samply" target="_blank" rel="noopener noreferrer">Google Play</a>.
        Once the app is installed, tapping a join link walks them through a short sequence:
      </p>
      <ol>
        <li><strong>Account creation.</strong> Participants create a participant account with an email address and password. Returning participants log in with their existing account.</li>
        <li><strong>Consent form</strong> (if your study has one). The text you entered in the study settings is shown in full. The participant must acknowledge it before proceeding.</li>
        <li><strong>Participant code prompt</strong> (if your study enables it). They type a custom identifier — a lab code, a participant number, anything you assign.</li>
        <li><strong>Group prompt</strong> (if your study enables it). They type the name of the group they belong to.</li>
      </ol>
      <p>
        After enrolment the study appears in their app, and Samply immediately registers any scheduled
        notifications for them.
      </p>

      {/* ── Accounts and email ───────────────────────────────────────────── */}
      <h2>Participant accounts and email addresses</h2>
      <p>
        Creating a participant account requires an email address. Samply stores this address and uses
        it only for authentication — it is never shown to the researcher or used for any other purpose.
        There are three reasons this is required:
      </p>
      <ul>
        <li><strong>One account per person.</strong> Requiring an account prevents a single person from enrolling multiple times from the same device.</li>
        <li><strong>Continuity across devices.</strong> If a participant gets a new phone, they can log in on the new device and continue the study without losing their history.</li>
        <li><strong>Password recovery.</strong> If a participant forgets their password, they can reset it via email.</li>
      </ul>

      {/* ── Codes ─────────────────────────────────────────────────────────── */}
      <h2>Participant codes</h2>
      <p>
        Enable <em>Ask participant for a code</em> in Edit study if you need to link Samply data to an
        external system — a lab ID, a REDCap record number, a Qualtrics respondent ID.
      </p>
      <p>
        The participant types their code during enrolment. You see it in the Participants table and can
        use it as a <a href="/docs/placeholders">URL placeholder</a> so the code is forwarded to your
        survey tool automatically.
      </p>
      <p>
        You can also pre-fill the code by appending <code>&amp;code=ABC</code> to the direct deep link —
        the participant will see the field already populated and just needs to confirm.
      </p>

      {/* ── Groups ────────────────────────────────────────────────────────── */}
      <h2>Groups at enrolment</h2>
      <p>
        Enable <em>Ask participant which group they belong to</em> in Edit study to collect a group
        assignment at the moment of joining. The participant types a group name; if that name already
        exists in the study, the participant is assigned to the same group.
      </p>
      <p>
        Groups collected at enrolment are typically used for condition assignment in designs where
        participants self-select. For researcher-controlled assignment, assign groups from the
        Participants table instead. Full details are in <a href="/docs/groups">Groups</a>.
      </p>

      {/* ── What you see ──────────────────────────────────────────────────── */}
      <h2>What you see after enrolment</h2>
      <p>
        Every enrolled participant appears in the <strong>Participants</strong> tab of your study. The table
        columns are:
      </p>
      <table>
        <thead>
          <tr>
            <th>Column</th>
            <th>What it contains</th>
          </tr>
        </thead>
        <tbody>
          {PARTICIPANT_TABLE_COLUMNS.map((r) => (
            <tr key={r.col}>
              <td>{r.col}</td>
              <td style={{ fontFamily: "var(--font-body)", fontSize: "1.3rem" }}>{r.desc}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* ── Re-joining ────────────────────────────────────────────────────── */}
      <h3>Re-joining and token refresh</h3>
      <p>
        If a participant taps the join link again — after reinstalling the app or switching devices —
        Samply matches them by Samply ID and updates their push notification token. They are not added
        as a duplicate. Their group, code, and response history are preserved.
      </p>

      {/* ── Leaving ───────────────────────────────────────────────────────── */}
      <h3>When a participant leaves</h3>
      <p>
        Participants can leave a study from within the Samply Research app. When they do, their row in
        the Participants table is marked <em>deactivated</em> and they stop receiving notifications.
        Their historical data — past notifications and responses — remains in the study for your records.
      </p>
    </>
  );
}
